server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ofms?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  mail:
    host: smtp.qq.com
    username: 2919586256@qq.com
    password: gsyuucucfgqjdfdb
    protocol: smtp
    default-encoding: UTF-8
  mvc:
    async:
      request-timeout: 60s

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:/mappers/*
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.demo.dao: debug


jodconverter:
  local:
    enabled: true
    office-home: D:\Allsoftware\Program Files\openOffice 4
    max-tasks-per-process: 10
    port-numbers: 8100



#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
